***************************************************************************

IPython post-mortem report

{'commit_hash': u'c963f6b',
 'commit_source': 'installation',
 'default_encoding': 'ISO-8859-1',
 'ipython_path': '/nfs/slac/g/ki/ki18/cpd/.local/lib/python2.7/site-packages/IPython',
 'ipython_version': '4.2.0',
 'os_name': 'posix',
 'platform': 'Linux-2.6.32-431.29.2.el6.x86_64-x86_64-with-redhat-6.8-Santiago',
 'sys_executable': '/afs/slac.stanford.edu/u/ki/cpd/.local/bin/python',
 'sys_platform': 'linux2',
 'sys_version': '2.7.6 (default, Nov 14 2013, 16:27:39) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)]'}

***************************************************************************



***************************************************************************

Crash traceback:

---------------------------------------------------------------------------
---------------------------------------------------------------------------
KeyboardInterruptPython 2.7.6: /afs/slac.stanford.edu/u/ki/cpd/.local/bin/python
                                                   Tue Dec  6 15:14:09 2016
A problem occurred executing Python code.  Here is the sequence of function
calls leading up to the error, with the most recent (innermost) call last.
/afs/slac.stanford.edu/u/ki/cpd/.local/lib/python2.7/lib-tk/Tkinter.pyc in __call__(self=<Tkinter.CallWrapper instance>, *args=('1316', '??', '??', '??', '66', '0', '-697670518', '??', '43', '398', '', '0', 'Mode_switch', '65406', '.116557008', '2', '47', '443', '66'))
   1450         return self.tk.call('image', 'names')
   1451 
   1452     def image_types(self):
   1453         """Return a list of all available image types (e.g. phote bitmap)."""
   1454         return self.tk.call('image', 'types')
   1455 
   1456 
   1457 class CallWrapper:
   1458     """Internal class. Stores function to call when some user
   1459     defined Tcl function is called e.g. after an event occurred."""
   1460     def __init__(self, func, subst, widget):
   1461         """Store FUNC, SUBST and WIDGET as members."""
   1462         self.func = func
   1463         self.subst = subst
   1464         self.widget = widget
-> 1465     def __call__(self, *args):
        global __call__ = undefined
        self = <Tkinter.CallWrapper instance at 0x6f28fc8>
        args = ('1316', '??', '??', '??', '66', '0', '-697670518', '??', '43', '398', '', '0', 'Mode_switch', '65406', '.116557008', '2', '47', '443', '66')
   1466         """Apply first function SUBST to arguments, than FUNC."""
   1467         try:
   1468             if self.subst:
   1469                 args = self.subst(*args)
   1470             return self.func(*args)
   1471         except SystemExit, msg:
   1472             raise SystemExit, msg
   1473         except:
   1474             self.widget._report_exception()
   1475 
   1476 
   1477 class XView:
   1478     """Mix-in class for querying and changing the horizontal position
   1479     of a widget's window."""
   1480 

KeyboardInterrupt: 

***************************************************************************

History of session input:hdf = pd.HDFStore('im3shape_galaxies.h5')hdfcat = hdf['catalog']cat.plot('ra', 'dec', kind='hexbin')cat.columnscat.plot('RA', 'DEC', kind='hexbin')
*** Last line of input (may not be in above history):
cat.plot('RA', 'DEC', kind='hexbin')
